# Remove these configuration records
# one by one as the offenses are removed from the code base.

Metrics/AbcSize:
  Max: 25 # Goal: 15

Metrics/CyclomaticComplexity:
  Max: 8 # Goal: 6

Metrics/PerceivedComplexity:
  Max: 10 # Goal: 7

Style/FrozenStringLiteralComment:
  Enabled: false
