language: ruby
cache: bundler

# For ruby compatibility, we test the highest and lowest minor versions only.
# For example, if our gemspec says `required_ruby_version = ">= 2.3.0"`, and
# ruby 2.5.0 has just been released, then we test 2.3 and 2.5, but not 2.4.
rvm:
  - 2.5.0
  - 2.3.6

env:
  global:
    - TRAVIS=true
  matrix:
    - DB=mysql
    - DB=postgres
    - DB=sqlite
sudo: false
gemfile:
  - gemfiles/ar_4.2.gemfile
  - gemfiles/ar_5.1.gemfile
  - gemfiles/ar_5.2.gemfile
matrix:
  fast_finish: true
addons:
  postgresql: "9.4"
